name: devtionary_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.3
  modern_launcher_name: ^1.0.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  path: ^1.9.0
  # Firebase Core (obligatorio)
  firebase_core: ^2.24.2
  
  # Firebase Auth para autenticación
  firebase_auth: ^4.17.4
  
  # Google Sign In para login con Google
  google_sign_in: ^6.2.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagenes/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

modern_launcher_name:
    name: "Devtionary"
    android: true
    ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/
    - assets/SubLogos/
    - assets/CatLogos/
