// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBjBP1dsfjxc07yFno6oLtAtDp9iWQeQ',
    appId: '1:703266325047:web:PENDIENTE_CREAR_APP_WEB',
    messagingSenderId: '703266325047',
    projectId: 'devtionary-27741',
    authDomain: 'devtionary-27741.firebaseapp.com',
    storageBucket: 'devtionary-27741.firebasestorage.app',
    measurementId: 'PENDIENTE_CREAR_APP_WEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyBjBP1dsfjxc07yFno6oLtAtDp9iWQeQ',
    appId: '1:703266325047:android:d8c337cca8d6ebd836f5b2',
    messagingSenderId: '703266325047',
    projectId: 'devtionary-27741',
    storageBucket: 'devtionary-27741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyBjBP1dsfjxc07yFno6oLtAtDp9iWQeQ',
    appId: '1:703266325047:ios:PENDIENTE_CREAR_APP_IOS',
    messagingSenderId: '703266325047',
    projectId: 'devtionary-27741',
    storageBucket: 'devtionary-27741.firebasestorage.app',
    iosBundleId: 'com.devtionary.devtionaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyBjBP1dsfjxc07yFno6oLtAtDp9iWQeQ',
    appId: '1:703266325047:macos:PENDIENTE_CREAR_APP_MACOS',
    messagingSenderId: '703266325047',
    projectId: 'devtionary-27741',
    storageBucket: 'devtionary-27741.firebasestorage.app',
    iosBundleId: 'com.devtionary.devtionaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyBjBP1dsfjxc07yFno6oLtAtDp9iWQeQ',
    appId: '1:703266325047:windows:PENDIENTE_CREAR_APP_WINDOWS',
    messagingSenderId: '703266325047',
    projectId: 'devtionary-27741',
    authDomain: 'devtionary-27741.firebaseapp.com',
    storageBucket: 'devtionary-27741.firebasestorage.app',
    measurementId: 'PENDIENTE_CREAR_APP_WEB',
  );
}
